import localFont from "next/font/local";
import "./globals.css";

const apercuMed = localFont({
  src: "./fonts/Apercu Pro Medium.woff",
  variable: "--font-apercu-med",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        //className={`${apercuMed.variable} antialiased`}
        className="font-apercuMed"
      >
        {children}
      </body>
    </html>
  );
}
